Repository AY2425S1-CS2103T-T12-2/tp, pull requests merged in 2024-10, with the labels that each got.

#59 Update Requirements section of DG after tutorial
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium

#65 Add filter feature
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/PersonTaggedWithPredicate.java
Labels: type.Story, type.Task, priority.High

#63 Modify help feature
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.Medium

#67 Update clear feature to support confirmation message
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ActualClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/ActualClearCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ActualClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Task, priority.High

#68 Add untag command
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UntagCommandParser.java
Labels: type.Task, priority.High

#82 Update use of contact/person in the DG
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High

#92 Reorganize tag display
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.Medium

#95 Update clear feature 2
  src/main/java/seedu/address/logic/commands/ActualClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/ActualClearCommandParser.java
  src/test/java/seedu/address/logic/commands/ActualClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/parser/ActualClearCommandParserTest.java
Labels: type.Bug, priority.Medium

#96 Update Add command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Enhancement, type.Bug, priority.High

#97 Improve FilterCommand
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/PersonTaggedWithPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTaggedWithPredicateTest.java
Labels: type.Enhancement, priority.High

#98 Enhance error checking for untag
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/parser/UntagCommandParser.java
  src/test/java/seedu/address/logic/commands/UntagCommandTest.java
  src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
Labels: type.Task, priority.High

#100 Modify help feature
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High

#101 Update ug features
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
Labels: type.Enhancement, priority.Medium

#104 Update UG for untag
  docs/UserGuide.md
Labels: type.Task, priority.High

#110 Update final UG for MVP
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#112 Update releases link for UG
  docs/UserGuide.md
Labels: priority.High

#123 Add sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Task, priority.Medium

#134 Merge branch for addw command
  src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
  src/main/java/seedu/address/logic/parser/AddWeddingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
  src/test/java/seedu/address/logic/parser/AddWeddingCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalWeddings.java
Labels: priority.High

#137 Add assign contact to wedding command with test cases.
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignContactToWeddingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignContactToWeddingCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/UntagCommandParser.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AssignContactToWeddingCommandTest.java
  src/test/java/seedu/address/logic/parser/AssignContactToWeddingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
Labels: type.Task, priority.High

#145 Update sample data for new users
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#148 Modify addw command
  src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
  src/main/java/seedu/address/logic/parser/AddWeddingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
  src/test/java/seedu/address/logic/parser/AddWeddingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditWeddingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalWeddings.java
Labels: priority.High

#149 Branch wedding panel UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/wedding/WeddingName.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WeddingCard.java
  src/main/java/seedu/address/ui/WeddingListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WeddingCard.fxml
  src/main/resources/view/WeddingListPanel.fxml
Labels: priority.Medium

#151 Update help command for v1.4 feature updates
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High

#154 Fix wedding update bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
Labels: priority.High

#156 Add validation for duplicate contact assigned to wedding
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
Labels: priority.High

#162 Update logic class diagram for DG
  docs/diagrams/LogicClassDiagram.puml
Labels: type.Task, priority.Medium

#168 Update dg UI component diagram
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: priority.Low

#170 Update ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.Low

#176 Update Help Message to match UG order
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Low

#177 Fix related to contacts not specified for addw usage
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, priority.Medium

#178 Restore CSS link to show error text
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug

#184 Add files for storing currentWeddingName
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task, priority.High

#188 Increase result panel height
  src/main/java/seedu/address/logic/commands/AssignContactToWeddingCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/UnassignContactFromWeddingCommand.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#196 Remove date validation for wedding
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: alpha-bug

#199 Show current wedding name in WeddingListPanel
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AssignContactToWeddingCommand.java
  src/main/java/seedu/address/logic/commands/UnassignContactFromWeddingCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CurrentWeddingNameCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WeddingListPanel.java
  src/main/resources/view/CurrentWeddingNameCard.fxml
  src/main/resources/view/WeddingListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement

#207 Implement colored Tags
  src/main/java/seedu/address/commons/core/TagColors.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/tag/ActiveTags.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/commons/core/TagColorsTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Low

#205 Debug delete wedding issues
  src/main/java/seedu/address/logic/commands/DeleteWeddingCommand.java
  src/main/resources/view/CurrentWeddingNameCard.fxml
  src/test/java/seedu/address/model/wedding/WeddingDateTest.java
  src/test/java/seedu/address/model/wedding/WeddingNameTest.java
Labels: type.Task, priority.High, alpha-bug

#212 Small fixes yxshrk
  src/main/java/seedu/address/logic/parser/UnassignContactFromWeddingCommandParser.java
  src/test/java/seedu/address/logic/parser/UnassignContactFromWeddingCommandParserTest.java
Labels: type.Bug, priority.Medium
