Repository AY2425S1-CS2103T-T12-2/tp, pull requests merged in 2024-09, with the labels that each got.

#15 Add adipanda2002 photo
  docs/images/adipanda2002.png
Labels: type.Task, priority.High

#17 Add maertan photo
  docs/images/maertan.png
Labels: type.Task, priority.High

#20 Add kikokidayo's photo
  docs/images/kikokidayo.png
Labels: type.Task, priority.High

#31 Update AboutUs.md for Ignatius' portion
  docs/AboutUs.md
Labels: priority.High

#28 Update AboutUs page
  docs/AboutUs.md
Labels: type.Enhancement, priority.High

#27 Add maertan AboutUs
  docs/AboutUs.md
Labels: type.Task, priority.High

#29 Update AboutUs page to include name and roles
  docs/AboutUs.md
Labels: type.Task, priority.High

#30 Update AboutUs page
  docs/AboutUs.md
Labels: type.Task, priority.High

#40 Update UI mockup
  docs/images/Ui.png
  docs/images/yxshrk.png
Labels: type.Enhancement, priority.High

#41 Update build status badge link to team repo
  README.md
Labels: type.Enhancement, priority.High

#43 Readme A3 A4 update
  README.md
  docs/AboutUs.md
  docs/index.md
Labels: type.Task, priority.High

#46 Final Update to README for site
  README.md
Labels: type.Task, priority.High

#47 Update DG - Glossary
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.High
